export const ACTION_TYPE = {
  INITIAL_DATA_FETCH: 'INITIAL_DATA_FETCH',
  FILTER_CHANGE: 'FILTER_CHANGE',
  FILTER_CLEAR: 'FILTER_CLEAR',
  MENU_TOGGLE: 'ACTIVE_MENU',
  RESET_MENU: 'RESET_MENU',
  SET_HISTORY: 'SET_HISTORY',
  SET_PLAYLIST: 'SET_PLAYLIST',
  SET_SINGLE_PLAYLIST: 'SET_SINGLE_PLAYLIST',
  SET_WATCH_LATER: 'SET_WATCH_LATER',
  SET_LIKED: 'SET_LIKED',
  RESET: 'RESET',
};
export const FILTER = {
  SEARCH: 'search',
  CATEGORY: 'category',
};
